const itemsPrincipal = [
  [
    {
      title: "Continúa donde quedaste",
      src: "/item1.jpg",
      width: 209,
      height: 284,
      alt: "itemPrincipal1",
      subtitle: "",
      a: "Ver más",
    },
    {
      title: "Mejores Ofertas",
      src: "/item2.jpg",
      width: 189,
      height: 204,
      alt: "itemPrincipal2",
      subtitle: "",
      a: "Compra todas las ofertas",
    },
    {
      title: "Ofertas en Equipos",
      src: "/item3.jpg",
      width: 389,
      height: 504,
      alt: "itemPrincipal3",
      subtitle: "",
      a: "Compra ahora",
    },
    {
      title: "Año nuevo, nuevos suministros",
      src: "/item4.jpg",
      width: 209,
      height: 254,
      alt: "itemPrincipal4",
      subtitle: "",
      a: "Compra productos de oficina y papelería",
    },
  ],
  [
    {
      title: "Decoración del hogar por menos de 50 USD",
      src: "/item5.jpg",
      width: 379,
      height: 304,
      alt: "itemPrincipal5",
      subtitle: "",
      a: "Compra ahora",
    },
    {
      title: "Juguetes por menos de 25 USD",
      src: "/item6.jpg",
      width: 379,
      height: 304,
      alt: "itemPrincipal6",
      subtitle: "",
      a: "Compra ahora",
    },
    {
      title: "Año Nuevo Lunar",
      src: "/item7.jpg",
      width: 379,
      height: 304,
      alt: "itemPrincipal7",
      subtitle: "",
      a: "Compra ahora",
    },
    {
      title: "Renueva tu espacio",
      src: "/item8.jpg",
      width: 379,
      height: 304,
      alt: "itemPrincipal8",
      subtitle: "",
      a: "Más Información",
    },
  ],
];

export default itemsPrincipal;
